implement DelegateChocoSources switch to enable source feed passing
mwrock/boxstarter pull request #320
Opened 2018-07-20 08:27 UTC by mwallnerks

A switch parameter for `Install-BoxstarterPackage` that passes locally configured Chocolatey sources to remote machines.

2018-07-20 08:28 UTC, mwallnerks commented
should be a soltion to #6

2018-07-20 08:34 UTC, gep13 requested changes

2018-07-20 08:34 UTC, gep13 commented on Boxstarter.Chocolatey/Install-BoxstarterPackage.ps1
> +This enables remote chocolatey installs to use the same NugetSources
Minor nit pick...
`chocolatey` -> `Chocolatey`

2018-07-20 08:34 UTC, gep13 commented on Boxstarter.Chocolatey/Install-BoxstarterPackage.ps1
> +as the local boxstarter install.
Minor nit pick...
`boxstarter` -> `Boxstarter`

2018-07-20 08:38 UTC, mwallner requested changes

2018-07-20 08:38 UTC, mwallner commented on Boxstarter.Chocolatey/Install-BoxstarterPackage.ps1
> +		if ($delegateSources) {
wrong identation ...

2018-07-20 10:10 UTC, pauby approved these changes
LGTM

2018-07-22 11:58 UTC, mwrock approved these changes
Looks great!

2018-07-23 08:20 UTC, gep13 approved these changes

2018-07-23 08:22 UTC, gep13 approved these changes
LGTM

2018-07-23 08:25 UTC, merged