[WIP] introduce command line switch 'StopOnFirstError'
mwrock/boxstarter pull request #402
Opened 2019-07-22 19:30 UTC by mwallner

It should be possible to tell Boxstarter to `stop` after it fails to install a Chocolatey package.

This aims to replace GH-296

See discussion at GH-382

2019-07-23 08:39 UTC, pauby requested changes

2019-07-23 08:39 UTC, pauby commented on Boxstarter.Bootstrapper/Init-Settings.ps1
> +if(!$Boxstarter.ContainsKey('ExitOnFirstError')) { $Boxstarter.ExitOnFirstError=$false }
Is the switch not `StopOnFirstError`? I also think we should be more clear what it is we are stopping for. So `StopOnFirstError` could be ANY error. Here we are only stopping when a package fails to install. So the switch should perhaps be renamed to `StopOnPackageFailure` (or something like that)?

2019-07-23 08:39 UTC, pauby commented on Boxstarter.Bootstrapper/Invoke-Boxstarter.ps1
> +      [switch]$ExitOnFirstError
Same as previous comment around the switch name. Can you also add blank lines between each parameter declaration?

2019-07-23 08:39 UTC, pauby commented on Boxstarter.Bootstrapper/Invoke-Boxstarter.ps1
> +        if($ExitOnFirstError){$Boxstarter.ExitOnFirstError=$ExitOnFirstError}
Same again with switch name.

2019-07-23 08:39 UTC, pauby commented on Boxstarter.Bootstrapper/Invoke-Boxstarter.ps1
>          if($encryptedPassword){$password = ConvertTo-SecureString -string $encryptedPassword}
Can we separate out the lines for the `if` statement (ie. they are not all on the same line)? And have spaces between the '='?

2019-07-23 08:39 UTC, pauby commented on Boxstarter.Bootstrapper/Invoke-Boxstarter.ps1
> +        Write-BoxstarterMessage "NoPassword is set to $($boxstarter.NoPassword) and RebootOk is set to $($Boxstarter.RebootOk) and the NoPassword parameter passed was $NoPassword, ExitOnFirstError is
The message here is adding each part with an `and` - can you keep to this and repace the comma with an `and` (or rewrite the whole message using commas with the final one an `and`)?

2019-07-23 08:39 UTC, pauby commented on Boxstarter.Bootstrapper/en-US/About_Boxstarter_Variable_In_Bootstrapper.help.txt
> +	ExitOnFirstError
Switch name again.

2019-07-23 08:39 UTC, pauby commented on Boxstarter.Chocolatey/Chocolatey.ps1
> +    $exitOnFirstError = (Get-PassedSwitch ExitOnFirstError $args) -Or $Boxstarter.ExitOnFirstError
Switch name again.

2019-07-23 08:39 UTC, pauby commented on Boxstarter.Chocolatey/Chocolatey.ps1
> +    Write-BoxstarterMessage "Will exit on first package error: $exitOnFirstError" -Verbose
Can we use the word 'stop' instead of 'exit' as that's more PowerShelly correct.

2019-07-23 08:39 UTC, pauby commented on Boxstarter.Chocolatey/Chocolatey.ps1
> +function Get-PassedSwitch($switchName, $origArgs) {
Can we have comment based function help here and make the function an Advanced function and have the parameter names Pascal Case?

Can we use the full cmdlet names rather than aliases?

2019-07-23 08:39 UTC, pauby commented on Boxstarter.Chocolatey/Chocolatey.ps1
> +    return $switchPresent
Return isn't needed here (and is kind of avoided in PowerShell). Just `$switchPresent` is enough.

2019-07-23 08:39 UTC, pauby commented on Boxstarter.Chocolatey/Chocolatey.ps1
> +    $candidateKeys = @()
I'm assuming `$switchName` and `$origArgs` are arrays of strings. Can this code not be replaced with something simpler - `[bool]($origArgs | where $_ -match "-+.*")` ? I maybe missing something however.

(I know it's using the same code as `Get-PassedArg`).

2019-07-23 08:39 UTC, pauby commented on Boxstarter.Chocolatey/Install-BoxstarterPackage.ps1
> +        [switch]$ExitOnFirstError
Switch name again.

2019-07-23 08:39 UTC, pauby commented on Boxstarter.Chocolatey/Install-BoxstarterPackage.ps1
>          [switch]$KeepWindowOpen,
Can you add blank lines between the parameter names?

2019-07-23 08:39 UTC, pauby commented on Boxstarter.Chocolatey/Install-BoxstarterPackage.ps1
> +        [switch]$ExitOnFirstError
Switch name and blank lines again.

2019-07-23 08:39 UTC, pauby commented on Boxstarter.Chocolatey/Invoke-ChocolateyBoxstarter.ps1
> +Invoke-ChocolateyBoxstarter $(if($bootstrapPackage){"-bootstrapPackage '$($bootstrapPackage -join ''',''')'"}) $(if($LocalRepo){"-LocalRepo $localRepo"})  $(if($DisableReboots){"-DisableReboots"} ) $
Switch name again.

Can we take the opportunity to rewrite this line of code to make it easier to read? Having embedded if statements inside the function call looks messy.

2019-07-23 19:43 UTC, mwallner commented on Boxstarter.Chocolatey/Invoke-ChocolateyBoxstarter.ps1
> +Invoke-ChocolateyBoxstarter $(if($bootstrapPackage){"-bootstrapPackage '$($bootstrapPackage -join ''',''')'"}) $(if($LocalRepo){"-LocalRepo $localRepo"})  $(if($DisableReboots){"-DisableReboots"} ) $
I tried to (see current status) - please tell me if this is okay now.

2019-07-23 20:07 UTC, mwallner commented on Boxstarter.Chocolatey/Chocolatey.ps1
> +    $candidateKeys = @()
I'd vote for keeping the helper function itself, but thanks for the idea for the regex :-)
```
function Get-PassedSwitch($switchName, $origArgs) {
    return [bool]($origArgs | Where-Object { $_ -match "^-+$switchName$" })
}
```

2019-07-23 20:11 UTC, mwallner commented on Boxstarter.Chocolatey/Chocolatey.ps1
> +    return [bool]($origArgs | Where-Object { $_ -match "^-+$switchName$" })
@pauby : should this (now) 1-liner still be an advanced function?

2019-10-03 16:12 UTC, pauby commented
@mwallner I'm assuming this is not ready to go (as the [WIP] is still in the title)?

2019-10-07 07:00 UTC, mwallner commented
sorry @pauby - forgot to remove the [WIP] title - imo this PR is ready

2019-10-09 20:07 UTC, pauby requested changes

2019-10-09 22:20 UTC, pauby commented on Boxstarter.Chocolatey/Invoke-ChocolateyBoxstarter.ps1
> +Invoke-ChocolateyBoxstarter $(if($bootstrapPackage){"-bootstrapPackage '$($bootstrapPackage -join ''',''')'"}) $(if($LocalRepo){"-LocalRepo $localRepo"})  $(if($DisableReboots){"-DisableReboots"} ) $
Looks good!

2019-10-09 22:26 UTC, pauby commented
Still a few items outstanding on this.

2019-10-10 18:28 UTC, mwallner commented on Boxstarter.Chocolatey/Chocolatey.ps1
> +    return [bool]($origArgs | Where-Object { $_ -match "^-+$switchName$" })
should I change / fix all the functions in the file, or only the ones I introduced/modified?

2020-02-18 10:59 UTC, pauby requested changes
Thanks for making all those changes Manfred. Just a few more options and this is good to go I think.

2020-02-18 10:59 UTC, pauby commented on Boxstarter.Chocolatey/Chocolatey.ps1
> +        $switchName,
Can we have a blank line between the parameters and can you add the data type of the parameters? and Title Case the parameter names?

2020-02-18 10:59 UTC, pauby commented on Boxstarter.Chocolatey/Chocolatey.ps1
> +    Process {
We don't need the Process block - can we remove it?

2020-02-18 10:59 UTC, pauby commented on Boxstarter.Chocolatey/Chocolatey.ps1
> +       return [bool]($origArgs | Where-Object { $_ -match "^-+$switchName$" })
The variables here should match the case of the parameters.

2020-02-18 10:59 UTC, pauby commented on Boxstarter.Bootstrapper/Init-Settings.ps1
> +if(!$Boxstarter.ContainsKey('StopOnPackageFailure')) { $Boxstarter.StopOnPackageFailure=$false }
Can we have the if statement on two lines to make it more readable (for all 3 of these statements)?

```
if(!$Boxstarter.ContainsKey('StopOnPackageFailure')) { 
    $Boxstarter.StopOnPackageFailure = $false
}
```

2020-02-26 20:10 UTC, pauby approved these changes

2020-02-26 20:10 UTC, merged

2020-02-26 20:11 UTC, pauby commented
Awesome work! Thanks for your contribution!